export const money = (n, cur = "PKR") =>
  n === null || n === undefined || Number.isNaN(+n) ? "-" : `${cur} ${Math.round(+n).toLocaleString("en-US")}`;

export const secs = (n) => (n === null || n === undefined ? "" : `${(+n).toFixed(1)}s`);

export function reportToMarkdown(r, b) {
  const cur = b.currency || "PKR";
  const list = (a) => a.map((x) => `- ${x}`).join("\n");
  return `# ${b.business_name} - Business Plan (BizPilot AI)

## Executive Summary
${r.executive_summary}

## Business Health
${r.business_health} (${r.health_score}/100)

## Key Numbers
- Revenue: ${money(r.revenue, cur)}
- Expenses: ${money(r.expenses, cur)}
- Estimated Profit: ${money(r.estimated_profit, cur)}
- Sales Trend: ${r.sales_trend}

## Main Problems
${list(r.main_problems)}

## Key Insights
${list(r.key_insights)}

## Recommended Strategy
${r.recommended_strategy}

## Marketing Plan
${r.marketing_plan}

## Action Plan
${list(r.action_plan)}

_Generated by BizPilot AI. AI-generated analysis; review before acting._
`;
}
